services:
  xnxpilot:
    build:
      context: .
      dockerfile: Dockerfile.xnxpilot
      args:
        USER_ID: ${HOST_UID:-1000}
        GROUP_ID: ${HOST_GID:-1000}
        USERNAME: ${USER:-developer}
    platform: linux/arm64  # Explicitly use Arm64 architecture
    privileged: true  # Add privileged mode
    volumes:
      - .:/home/${USER:-developer}/workspace/xnxpilot
      # Don't mount host passwd and group files as read-only
      # as they can cause issues with user/group identification
    ports:
      - "13000:8000"  # Adjust as needed for your application
    environment:
      - PYTHONPATH=/home/${USER:-developer}/workspace/xnxpilot
      - USER=${USER:-developer}
      - HOME=/home/${USER:-developer}
    # Don't set the user explicitly, let the container use the user created in Dockerfile
    # user: "${UID:-1000}:${GID:-1000}"
    working_dir: /home/${USER:-developer}/workspace/xnxpilot
    tty: true
    stdin_open: true

